//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoosterCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int company_id { get; set; }
        public string company_name { get; set; }
        public string file_name { get; set; }
        public byte[] data { get; set; }
    }
}
