//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoosterCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int task_id { get; set; }
        public string task_name { get; set; }
        public string status { get; set; }
        public string refer_type { get; set; }
        public string refer_name { get; set; }
        public string priority { get; set; }
        public string des { get; set; }
    }
}
